### PR TITLE
Skip failing Python 3.13 tests on musl

### PR DESCRIPTION
**Pull request by cdce8p**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
@cdce8p Why would we add a patch instead of setting the `PROFILE_TASK` environment variable?

../Frenck

**Comment by cdce8p** [comment]
Opened #281 to disable the PGO tests completely. That's what the official docker image does. I'd prefer to just skip the failing tests (i.e. this PR) as it would help us notice any changes / new failures. However, both PRs would work.

**Comment by frenck** [comment]
> I'd prefer to just skip the failing tests (i.e. this PR) as it would help us notice any changes / new failures. However, both PRs would work.

That makes total sense 👍

**Review by frenck — APPROVED** [review]
Thanks, @cdce8p 👍 

../Frenck

**Pull request merged**
