### PR TITLE
Backport Morsel creation speed up patch from cpython gh-126156

### PR DESCRIPTION
**Pull request by bdraco**
Improved performances of creating :py:class:`~http.cookies.Morsel` objects by a factor of 3.8x.

Should also get backported to 3.13 when it becomes available

Backport of https://github.com/python/cpython/commit/dd3c0fa3fd2795326dae0e0ed63c668f5506cf32

### CODE REVIEW

**Comment by edenhaus** [comment]
Python 3.13 was merged and therefore now available

**Review by frenck — APPROVED** [review]
Can you add it to the 3.13 too?

**Review by frenck — CHANGES_REQUESTED** [review]
Using the right button this time.

**Comment by bdraco** [comment]
Pushed the patch to 3.13 as well

Will mark it ready for review if CI passes.

Looks like things are busy now so will need to come back and check it later

**Comment by bdraco** [comment]
#7 7.301 patching file Lib/http/cookies.py

It looks like its patching ok on 3.12 and 3.13

**Review by frenck — APPROVED** [review]
Thanks, @bdraco 👍 

../Frenck

**Pull request merged**
